using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Pathfinding;
using System.Linq;

//Contains all of the enemy-specific logic
public class Enemy : MonoBehaviour
{
    public float speed = 1f;
    //A distance at which the enemy will attemt to shoot at the player
    public float playerShootDistance = 8.0f;
    //A distance at which the enemy will run away from the player
    public float runAwayDistance = 0.0f;
    public GameObject healthBar = null;
    [HideInInspector]
    public bool isDead = false;
    public bool CanBeHijacked { get
        {
            Damage damageScript = GetComponent<Damage>();
            return (float)(damageScript.bodyHealth) / damageScript.maxBodyHealth <= 0.5f;
        }
    }
    public bool shouldRunAway = false;
    
    //Used for pathfinding
    private Path path;
    private Seeker seeker;
    private int currentWaypoint = 0;
    private float nextWaypointDistance = 3f;
    
    private Rigidbody2D rb;
    private bool isFacingLeft = false;
    private bool canShoot = false;

    private void Start()
    {
        seeker = GetComponent<Seeker>();
        rb = GetComponent<Rigidbody2D>();

        InvokeRepeating("UpdatePath", 0f, .5f);
        InvokeRepeating("ShootAtPlayer", Random.Range(1.0f, 3.0f), 2.0f);

        SpawnerManager.mainManager.RegisterEnemySpawn();
    }

    //AStar project's navigation setup
    void UpdatePath()
    {
        if (seeker.IsDone())
        {
            if (Player.playerObject != null)
            {
                seeker.StartPath(rb.position, Player.playerObject.transform.position, OnPathComplete);
            }
        }
            
    }

    //Periodical attempt to shoot at the player
    private void ShootAtPlayer()
    {
        if (Player.playerObject == null || Player.playerObject.GetComponent<Player>().isDead || this.isDead)
            return;

        if (canShoot)
        {
            List<Weapon> availableWeapons = new List<Weapon>(GetComponentsInChildren<Weapon>());
            if (availableWeapons.Any(w => w.IsOnCooldown))
                return;
            Weapon chosenWeapon = availableWeapons[Random.Range(0, availableWeapons.Count)];
            chosenWeapon.UseWeapon();
        }
    }

    //What happens when the enemy script is turned off during assimilation or death
    private void OnDisable()
    {
        CancelInvoke();

        GetComponent<Seeker>().enabled = false;

        HandMovement[] handMovementScripts = gameObject.GetComponentsInChildren<HandMovement>();
        foreach (HandMovement movementScript in handMovementScripts)
        {
            movementScript.aimTowardsPlayer = false;
        }
        Destroy(healthBar);

        //Disabling this script is considered enemy's death so it's reported to the appropriate managers
        SpawnerManager.mainManager.RegisterEnemyDeath();
        SceneGoalManager.goalManager.RegisterEnemyDeath();
    }

    //Registering a new movement path after completing the current one
    void OnPathComplete(Path path)
    {
        if(!path.error)
        {
            this.path = path;
            currentWaypoint = 0;
        }
    }

    private void FixedUpdate()
    {
        //Enemies don't do anything when the player is dead
        if (Player.playerObject == null || Player.playerObject.GetComponent<Player>().isDead || this.isDead)
            return;

        Animator animator = gameObject.GetComponentInChildren<Animator>();
        animator.SetBool("IsMoving", Mathf.Abs(rb.velocity.x) >= 0.5f);
        bool isMovingRight = rb.velocity.x > 0;

        //XOR operation. Either the character moves right and is facing right or is moving left and is facing left
        bool isMovingForward = isMovingRight ^ gameObject.transform.localRotation.y != 0.0f;

        animator.SetBool("IsMovingForward", isMovingForward);

        //Enemies are always facing the player, even when retreating
        Vector3 playerPosition = Player.playerObject.transform.position;
        if (playerPosition.x > transform.position.x && isFacingLeft)
        {
            gameObject.transform.rotation = Quaternion.Euler(0.0f, 0.0f, 0.0f);
            isFacingLeft = false;
        }
        else if (playerPosition.x < transform.position.x && !isFacingLeft)
        {
            gameObject.transform.rotation = Quaternion.Euler(0.0f, 180.0f, 0.0f);
            isFacingLeft = true;
        }

        //Check if the enemy's line of sight is not blocked by any obstacles
        RaycastHit2D enemyLineOfSight =  Physics2D.Linecast(transform.position, playerPosition, 1 << LayerMask.GetMask(new string[] { "Ground", "Wall" }));

        //Determines whether the enemy should chase the player, stand still or run away from him
        if ((playerPosition - transform.position).magnitude >= playerShootDistance || (shouldRunAway && (playerPosition - transform.position).magnitude <= runAwayDistance))
        {
            //Movement is based on the waypoints generated by the AStar project
            if (path == null)
                return;
            else if (currentWaypoint >= path.vectorPath.Count)
            {
                return;
            }

            Vector2 direction = ((Vector2)path.vectorPath[currentWaypoint] - rb.position).normalized;
            if (shouldRunAway && (playerPosition - transform.position).magnitude <= runAwayDistance)
            {
                direction *= -1;
            }

            Vector2 force = new Vector2(direction.x * speed, rb.velocity.y);

            rb.velocity = force;

            //Determines whether the enemy should jump, try to jump off a platform or neither of them
            if (direction.y != 1.0f)
            {
                Jumping jumpScript = gameObject.GetComponent<Jumping>();
                if (direction.y > 0.99f) //Jumping threshold
                {
                    jumpScript.TryJump();
                }
                else if (direction.y < -0.85f) // Jumping off threshold
                {
                    StartCoroutine(jumpScript.TryJumpOffPlatform());
                }
            }

            //Advancing checkpoints (AStar)
            float distance = Vector2.Distance(rb.position, path.vectorPath[currentWaypoint]);

            if (distance < nextWaypointDistance)
            {
                currentWaypoint++;
            }

            if(enemyLineOfSight.collider != null)
            {
                canShoot = false;
            }
            else
            {
                canShoot = true;
            }
            
        }
        
    }

    private void OnDrawGizmos()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(transform.position, playerShootDistance);
        Gizmos.color = Color.white;
        Gizmos.DrawWireSphere(transform.position, runAwayDistance);
    }
}
